<a href="https://colab.research.google.com/github/PabloTM-00/PabloTM-00/blob/main/Lab_S03_Analisis_y_Transformacion_Pablo_Torres.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio S03 - Análisis y Transformación de Datos

Transformación de variables categóricas (Label Encoding y One-Hot
Encoding) y escalado/estandarización de características numéricas (StandardScaler y
MinMaxScaler), aplicadas en **dos conjuntos de datos**:

- **1:** el dataset entregado , `Churn_Modelling.csv` (clientes de un banco,
  con una columna `Exited` que indica si el cliente se fue o no — "churn").
- **2:**  dataset propio ,  mi **playlist de
  Spotify** (`playlist.csv`), reproduciendo exactamente el mismo flujo de transformación.

#PARTE 1 — Transformación de Datos `Churn_Modelling.csv`

## 1. Transformamos los datos

In [ ]:
# se importan las librerias necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [ ]:
from google.colab import files
files.upload()

# carga datos
data_frame = pd.read_csv("2_3_2_Churn_Modelling.csv")

Saving 2_3_2_Churn_Modelling.csv to 2_3_2_Churn_Modelling.csv

In [ ]:
# visualización del conjunto de datos
data_frame

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
# 10 filas al azar para ver un muestreo general del conjunto de datos
data_frame.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
8496,8497,15705735,Onyekachi,577,Spain,Male,43,3,0.00,2,1,1,135008.92,0
2970,2971,15595228,Wanliss,815,France,Male,45,7,0.00,1,0,1,52885.23,1
1323,1324,15629244,Bryant,635,Spain,Male,50,7,159453.64,2,0,0,54560.79,1
5289,5290,15741195,Okechukwu,613,Spain,Male,19,5,0.00,1,1,1,176903.35,0
9744,9745,15785358,Gresswell,586,Germany,Male,46,8,106968.96,1,1,1,79366.98,1
2584,2585,15754537,Ko,748,France,Male,40,0,0.00,1,0,0,60416.76,0
2323,2324,15784676,Fanucci,583,France,Male,51,6,125268.03,2,1,0,165082.25,0
5064,5065,15671243,Y?,558,France,Female,47,9,0.00,2,1,0,103787.28,0
7492,7493,15776545,Napolitani,682,France,Male,28,10,200724.96,1,0,1,82872.64,1
642,643,15809663,Donaldson,583,France,Female,27,1,125406.58,1,1,1,110784.42,0

In [ ]:
# calcular estadisticas descriptivas como la media o desviacion estandar para cada columna numerica del dataset, hay mucha diferencia en los datos por eso se debera escalar los datos
data_frame.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
# chequeo de nulos por columna y conteo
for feature in data_frame.columns:
  print('Total de valores nulos de', feature, '=', data_frame[feature].isna().sum())
# observamos que no hay nulos

Total de valores nulos de RowNumber = 0
Total de valores nulos de CustomerId = 0
Total de valores nulos de Surname = 0
Total de valores nulos de CreditScore = 0
Total de valores nulos de Geography = 0
Total de valores nulos de Gender = 0
Total de valores nulos de Age = 0
Total de valores nulos de Tenure = 0
Total de valores nulos de Balance = 0
Total de valores nulos de NumOfProducts = 0
Total de valores nulos de HasCrCard = 0
Total de valores nulos de IsActiveMember = 0
Total de valores nulos de EstimatedSalary = 0
Total de valores nulos de Exited = 0

In [ ]:
# muestra el tipo de dato de cada columna, util para saber cual es numerica/categorica y que trans. aplicar a cada una
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:

# seleccion de metricas para el analisis, se descartan rownumber, customerid y surname ya que no aportan nada para la prediccion, asi como la ultima
X = data_frame.iloc[:, 3:-1].values

# se separa exited como columna para variable objetivo
y = data_frame.iloc[:, -1].values

In [ ]:
# comprobacion visual de que columnas van a ser las predictoras
pd.DataFrame(X).head(10)

     0       1       2   3  4          5  6  7  8          9
0  619  France  Female  42  2        0.0  1  1  1  101348.88
1  608   Spain  Female  41  1   83807.86  1  0  1  112542.58
2  502  France  Female  42  8   159660.8  3  1  0  113931.57
3  699  France  Female  39  1        0.0  2  0  0   93826.63
4  850   Spain  Female  43  2  125510.82  1  1  1    79084.1
5  645   Spain    Male  44  8  113755.78  2  1  0  149756.71
6  822  France    Male  50  7        0.0  2  1  1    10062.8

In [ ]:

pd.DataFrame(y).head(10)

   0
0  1
1  0
2  1
3  0
4  0
5  1
6  0

**1.1. Transformación de Variables Categóricas.**

Una variable categórica es aquella cuyo valores vienen fr un conjunto limitado de elementos.
Deben ser tratadas porque muchos de los algoritmos que usaré requieren que las variables sean numéricas

Pasos:
1. Borrar las variables categóricas que no aportan mucho valor al análisis

2. Label Encoding. Asigna a cada valor de la lista un número entero
   diferente.

3. One-hot-encoding. Crea nuevas columnas indicando la presencia de cada posible
   valor en el set de datos

In [ ]:

# aplicarlo al dataset real.
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# ejemolo con 3 categorias; frio templado y calor
data = ['frio', 'frio', 'templado', 'frio', 'calor', 'calor', 'templado','frio', 'templado', 'calor']
values = array(data)
print('Valores:',values)

# label encoding para convertir cada categoria de texto en un entero
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print('Label encoder integer:',integer_encoded)

# one hot encoding que a partir de los enteros crea una columna binaria por cada categoriap osible
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print('one-hot encoder:\n', onehot_encoded)

# inverse transform para volver del numero ya codificado al valor original categorico
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted) # MUESTRA LA VARIABLE QUE MÁS VECES SE TRANSFORMÓ.

Valores: ['frio' 'frio' 'templado' 'frio' 'calor' 'calor' 'templado' 'frio'
 'templado' 'calor']
Label encoder integer: [1 1 2 1 0 0 2 1 2 0]
one-hot encoder:
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
['frio']

**1.1.1. Comenzamos con la columna Género.**

In [ ]:

# lable encoding a la columna gender
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
pd.DataFrame(X)

        0        1  2   3   4          5  6  7  8          9
0     619   France  0  42   2        0.0  1  1  1  101348.88
1     608    Spain  0  41   1   83807.86  1  0  1  112542.58
2     502   France  0  42   8   159660.8  3  1  0  113931.57
3     699   France  0  39   1        0.0  2  0  0   93826.63
4     850    Spain  0  43   2  125510.82  1  1  1    79084.1
...   ...      ... ..  ..  ..        ... .. .. ..        ...
9995  771   France  1  39   5        0.0  2  1  0   96270.64
9996  516   France  1  35  10   57369.61  1  1  1  101699.77
9997  709   France  0  36   7        0.0  1  0  1   42085.58
9998  772  Germany  1  42   3   75075.31  2  1  0   92888.52
9999  792   France  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [ ]:

# revisamos los valores unicos para la columna geography para saber si es apropiado el one hot encoding
pd.DataFrame(X)[1].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

3 valores distintos por lo que se sumaran 3 columas mostrando 1 o 0 para presencia o ausencia

In [ ]:

# aplicamos one hot encoding a la columna geography ya que tiene las 3 columnas que vimos antes
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
pd.DataFrame(X)

# mostramos el nuevo conjunto transformado con la variable geografia, observamos que ahora hay 3 columnas (1 por pais)

       0    1    2    3  4   5   6          7  8  9  10         11
0     1.0  0.0  0.0  619  0  42   2        0.0  1  1  1  101348.88
1     0.0  0.0  1.0  608  0  41   1   83807.86  1  0  1  112542.58
2     1.0  0.0  0.0  502  0  42   8   159660.8  3  1  0  113931.57
3     1.0  0.0  0.0  699  0  39   1        0.0  2  0  0   93826.63
4     0.0  0.0  1.0  850  0  43   2  125510.82  1  1  1    79084.1
...   ...  ...  ...  ... ..  ..  ..        ... .. .. ..        ...
9995  1.0  0.0  0.0  771  1  39   5        0.0  2  1  0   96270.64
9996  1.0  0.0  0.0  516  1  35  10   57369.61  1  1  1  101699.77
9997  1.0  0.0  0.0  709  0  36   7        0.0  1  0  1   42085.58
9998  0.0  1.0  0.0  772  1  42   3   75075.31  2  1  0   92888.52
9999  1.0  0.0  0.0  792  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 12 columns]

**1.2. Escalar y Estandarizar las Características.**

Podemos usar:
1. StandardScaler
2. MinMaxScaler

In [ ]:

# standarscaler para estandarizar cada columna tenga media 0 y desvio estandar 1
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scaled_data = sc.fit_transform(X)
pd.DataFrame(scaled_data).head(10)

#mostramos nuevo dataframe

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.997204,-0.578736,-0.573809,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-1.002804,-0.578736,1.742740,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,0.997204,-0.578736,-0.573809,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,0.997204,-0.578736,-0.573809,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,-1.002804,-0.578736,1.742740,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276
5,-1.002804,-0.578736,1.742740,-0.057205,0.912419,0.484225,1.032908,0.597329,0.807737,0.646092,-1.030670,0.863650
6,0.997204,-0.578736,-0.573809,1.774174,0.912419,1.056346,0.687130,-1.225848,0.807737,0.646092,0.970243,-1.565487
7,-1.002804,1.727904,-0.573809,-2.840488,-1.095988,-0.946079,-0.350204,0.618019,4.246377,0.646092,-1.030670,0.334854
8,0.997204,-0.578736,-0.573809,-1.547141,0.912419,0.484225,-0.350204,1.050820,0.807737,-1.547768,0.970243,-0.437329
9,0.997204,-0.578736,-0.573809,0.346319,0.912419,-1.136786,-1.041760,0.931463,-0.911583,0.646092,0.970243,-0.493230

In [ ]:

# minmaxscaler reescala cada columna para que todas las variables queden en el mismo "rango"
scaler = MinMaxScaler()
scaled_data_1 = sc.fit_transform(X) # nuevo dataframe
pd.DataFrame(scaled_data_1).head(5)

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.997204,-0.578736,-0.573809,-0.326221,-1.095988,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-1.002804,-0.578736,1.742740,-0.440036,-1.095988,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,0.997204,-0.578736,-0.573809,-1.536794,-1.095988,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,0.997204,-0.578736,-0.573809,0.501521,-1.095988,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,-1.002804,-0.578736,1.742740,2.063884,-1.095988,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276
5,-1.002804,-0.578736,1.742740,-0.057205,0.912419,0.484225,1.032908,0.597329,0.807737,0.646092,-1.030670,0.863650
6,0.997204,-0.578736,-0.573809,1.774174,0.912419,1.056346,0.687130,-1.225848,0.807737,0.646092,0.970243,-1.565487
7,-1.002804,1.727904,-0.573809,-2.840488,-1.095988,-0.946079,-0.350204,0.618019,4.246377,0.646092,-1.030670,0.334854
8,0.997204,-0.578736,-0.573809,-1.547141,0.912419,0.484225,-0.350204,1.050820,0.807737,-1.547768,0.970243,-0.437329
9,0.997204,-0.578736,-0.573809,0.346319,0.912419,-1.136786,-1.041760,0.931463,-0.911583,0.646092,0.970243,-0.493230

In [ ]:

# estadisticas descriptivas de los datos una vez ya aplicamos standardScaler
pd.DataFrame(scaled_data).describe()

,0,1,2,3,4,5,6,7,8,9,10,11
count,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04
mean,1.143974e-16,-1.989520e-17,5.684342e-17,-4.824585e-16,8.455459e-17,2.414069e-16,-1.325162e-16,6.218670e-15,7.105427e-19,-2.273737e-17,6.394885e-18,3.519141e-15
std,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00
min,-1.002804e+00,-5.787359e-01,-5.738092e-01,-3.109504e+00,-1.095988e+00,-1.994969e+00,-1.733315e+00,-1.225848e+00,-9.115835e-01,-1.547768e+00,-1.030670e+00,-1.740268e+00
25%,-1.002804e+00,-5.787359e-01,-5.738092e-01,-6.883586e-01,-1.095988e+00,-6.600185e-01,-6.959818e-01,-1.225848e+00,-9.115835e-01,-1.547768e+00,-1.030670e+00,-8.535935e-01
50%,9.972039e-01,-5.787359e-01,-5.738092e-01,1.522218e-02,9.124191e-01,-1.832505e-01,-4.425957e-03,3.319639e-01,-9.115835e-01,6.460917e-01,9.702426e-01,1.802807e-03
75%,9.972039e-01,1.727904e+00,-5.738092e-01,6.981094e-01,9.124191e-01,4.842246e-01,6.871299e-01,8.199205e-01,8.077366e-01,6.460917e-01,9.702426e-01,8.572431e-01
max,9.972039e-01,1.727904e+00,1.742740e+00,2.063884e+00,9.124191e-01,5.061197e+00,1.724464e+00,2.795323e+00,4.246377e+00,6.460917e-01,9.702426e-01,1.737200e+00

In [ ]:

pd.DataFrame(scaled_data_1).describe()

,0,1,2,3,4,5,6,7,8,9,10,11
count,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04
mean,1.143974e-16,-1.989520e-17,5.684342e-17,-4.824585e-16,8.455459e-17,2.414069e-16,-1.325162e-16,6.218670e-15,7.105427e-19,-2.273737e-17,6.394885e-18,3.519141e-15
std,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00,1.000050e+00
min,-1.002804e+00,-5.787359e-01,-5.738092e-01,-3.109504e+00,-1.095988e+00,-1.994969e+00,-1.733315e+00,-1.225848e+00,-9.115835e-01,-1.547768e+00,-1.030670e+00,-1.740268e+00
25%,-1.002804e+00,-5.787359e-01,-5.738092e-01,-6.883586e-01,-1.095988e+00,-6.600185e-01,-6.959818e-01,-1.225848e+00,-9.115835e-01,-1.547768e+00,-1.030670e+00,-8.535935e-01
50%,9.972039e-01,-5.787359e-01,-5.738092e-01,1.522218e-02,9.124191e-01,-1.832505e-01,-4.425957e-03,3.319639e-01,-9.115835e-01,6.460917e-01,9.702426e-01,1.802807e-03
75%,9.972039e-01,1.727904e+00,-5.738092e-01,6.981094e-01,9.124191e-01,4.842246e-01,6.871299e-01,8.199205e-01,8.077366e-01,6.460917e-01,9.702426e-01,8.572431e-01
max,9.972039e-01,1.727904e+00,1.742740e+00,2.063884e+00,9.124191e-01,5.061197e+00,1.724464e+00,2.795323e+00,4.246377e+00,6.460917e-01,9.702426e-01,1.737200e+00

# Parte 2 — Dataset Propio: `playlist.csv`


Seguimos el mismo flujo de antes sobre mi dataset con metadatos de las canciones, calculadas por Spotify

**Equivalencia entre ambos datasets:**

| Churn_Modelling         | Playlist (Spotify)                                          |
|--------------------------|---------------------------------------------------------------|
| `Gender` (2 categorías, Label Encoding) | `Explicit` (2 categorías: True/False)          |
| `Geography` (3 categorías, One-Hot)     | `Time Signature` (3 categorías principales: 3, 4, 5) |
| `Exited` (variable objetivo)            | `Popularity` (variable objetivo)                |
| Resto de columnas numéricas             | Audio features: Danceability, Energy, Loudness, etc. |

In [ ]:
from google.colab import files
files.upload()

data_frame_2 = pd.read_csv("playlist.csv", encoding="utf-8-sig", low_memory=False)
data_frame_2

Saving playlist.csv to playlist.csv

,Track URI,Track Name,Album Name,Artist Name(s),Release Date,Duration (ms),Popularity,Explicit,Added By,Added At,...,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature
0,spotify:track:0TZJzQCOkVtyzjOD8wzAHh,FATAL FANTASSY,FATAL FANTASSY,Alvaro Diaz;Tainy,2023-10-27,149360.0,48.0,False,u88iadq62r1eebsjfcziz6ymd,2023-10-27T17:14:58Z,...,2.0,-4.730,1.0,0.0499,0.09280,0.000000,0.7730,0.377,124.999,4.0
1,spotify:track:5Sj46dsTWjcgyiWuxGKGul,2030,2030,La Pantera,2024-06-07,122659.0,37.0,True,u88iadq62r1eebsjfcziz6ymd,2024-06-08T17:36:15Z,...,8.0,-4.597,1.0,0.0391,0.26800,0.000003,0.0902,0.845,90.258,4.0
2,spotify:track:6RmnotfWeDu72fXhpo26Bq,otra vez,BAHÍA DUCATI,Feid;Alvaro Diaz,2020-09-11,205000.0,61.0,False,u88iadq62r1eebsjfcziz6ymd,2024-01-25T17:43:25Z,...,9.0,-7.439,1.0,0.0992,0.01990,0.000000,0.1240,0.216,145.903,4.0
3,spotify:track:0tHzUXLKk7p0wzMZMMEl8y,CANIJO,CANIJO,Judeline,2023-06-15,141586.0,57.0,False,u88iadq62r1eebsjfcziz6ymd,2025-07-05T16:29:53Z,...,2.0,-8.496,0.0,0.3490,0.56800,0.000015,0.1740,0.410,84.410,5.0
4,spotify:track:60SnwR5bQXskXxqfSqVDgg,MARGIELA,MARGIELA,Omar Courtz,2022-02-11,171291.0,0.0,False,u88iadq62r1eebsjfcziz6ymd,2023-10-21T09:23:54Z,...,8.0,-7.356,0.0,0.3820,0.37000,0.000015,0.1000,0.656,90.078,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1222,spotify:track:3gE4eQH3K83Sght0ZLvuBK,MIA,X 100PRE,Bad Bunny;Drake,2018-12-23,210367.0,80.0,False,u88iadq62r1eebsjfcziz6ymd,2026-08-03T00:39:31Z,...,2.0,-7.599,0.0,0.0332,0.49400,0.000004,0.4470,0.337,147.984,4.0
1223,spotify:track:1PSVEVXH6vrkntmQX34uzZ,No pega igual (Stuck on replay),No pega igual (Stuck on replay),Barry B,2026-07-23,185118.0,59.0,False,u88iadq62r1eebsjfcziz6ymd,2026-08-03T15:59:45Z,...,7.0,-2.674,0.0,0.0537,0.16700,0.000000,0.7630,0.962,165.971,4.0
1224,spotify:track:7mjWqfMjappj2v1Iw3rXeR,LA SACAPUNTAS,LA SACAPUNTAS,Kabasaki;Zeno El Faraón;l0rna;Kristina,2025-11-13,235812.0,67.0,True,u88iadq62r1eebsjfcziz6ymd,2026-08-04T14:35:55Z,...,7.0,-3.457,0.0,0.0375,0.00119,0.000165,0.1880,0.316,139.983,4.0
1225,spotify:track:7dcxWXVc1xc72xG9KFvZhT,Noche Without You,Noche Without You,Skrillex;Feid,2026-06-04,203571.0,56.0,False,u88iadq62r1eebsjfcziz6ymd,2026-08-05T23:39:43Z,...,6.0,-4.017,0.0,0.0501,0.16700,0.000298,0.0866,0.624,171.940,4.0
1226,spotify:track:32oPtn23E4YAoSsGSNm3J3,FLAKITO,EL BAIFO,Quevedo,2026-04-24,194609.0,74.0,False,u88iadq62r1eebsjfcziz6ymd,2026-08-06T16:08:50Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# a diferencia del dataset anterior , la playlist si tiene varios nulos
for feature in data_frame_2.columns:
  print('Total de valores nulos de', feature, '=', data_frame_2[feature].isna().sum())

Total de valores nulos de Track URI = 4
Total de valores nulos de Track Name = 0
Total de valores nulos de Album Name = 8
Total de valores nulos de Artist Name(s) = 8
Total de valores nulos de Release Date = 12
Total de valores nulos de Duration (ms) = 4
Total de valores nulos de Popularity = 4
Total de valores nulos de Explicit = 4
Total de valores nulos de Added By = 0
Total de valores nulos de Added At = 0
Total de valores nulos de Genres = 456
Total de valores nulos de Record Label = 0
Total de valores nulos de Danceability = 12
Total de valores nulos de Energy = 12
Total de valores nulos de Key = 12
Total de valores nulos de Loudness = 12
Total de valores nulos de Mode = 12
Total de valores nulos de Speechiness = 12
Total de valores nulos de Acousticness = 12
Total de valores nulos de Instrumentalness = 12
Total de valores nulos de Liveness = 12
Total de valores nulos de Valence = 12
Total de valores nulos de Tempo = 12
Total de valores nulos de Time Signature = 12

In [ ]:

# conocemos los datos de cada columna como antes para ver que transformamos
data_frame_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1227 entries, 0 to 1226
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Track URI         1223 non-null   object
 1   Track Name        1227 non-null   object
 2   Album Name        1219 non-null   object
 3   Artist Name(s)    1219 non-null   object
 4   Release Date      1215 non-null   object
 5   Duration (ms)     1223 non-null   float64
 6   Popularity        1223 non-null   float64
 7   Explicit          1223 non-null   object
 8   Added By          1227 non-null   object
 9   Added At          1227 non-null   object
 10  Genres            771 non-null    object
 11  Record Label      1227 non-null   object
 12  Danceability      1215 non-null   float64
 13  Energy            1215 non-null   float64
 14  Key               1215 non-null   float64
 15  Loudness          1215 non-null   float64
 16  Mode              1215 non-null   float64
 17  Speechiness       1215 non-null   float64
 18  Acousticness      1215 non-null   float64
 19  Instrumentalness  1215 non-null   float64
 20  Liveness          1215 non-null   float64
 21  Valence           1215 non-null   float64
 22  Tempo             1215 non-null   float64
 23  Time Signature    1215 non-null   float64
dtypes: float64(14), object(10)
memory usage: 230.2+ KB

In [ ]:
# aqui si hay que tratar los nulos, se descartan las filas con algun nulo en la columna que use nuestra variable predictora objetiva (son muy pocas)
columnas_a_usar = [
    'Duration (ms)', 'Time Signature', 'Explicit', 'Danceability', 'Energy', 'Key',
    'Loudness', 'Mode', 'Speechiness', 'Acousticness', 'Instrumentalness', 'Liveness',
    'Valence', 'Tempo', 'Popularity'
]
data_frame_2 = data_frame_2.dropna(subset=columnas_a_usar).reset_index(drop=True)
data_frame_2.shape

(1215, 24)

In [ ]:
# seleccionamos las variables para el analisis, descartando las de texto o cualquiera que no aporte valor de prediccion
X = data_frame_2[[
    'Duration (ms)', 'Time Signature', 'Explicit', 'Danceability', 'Energy', 'Key',
    'Loudness', 'Mode', 'Speechiness', 'Acousticness', 'Instrumentalness', 'Liveness',
    'Valence', 'Tempo'
]].values

# la variable objetivo sera la popularidad
y = data_frame_2['Popularity'].values

In [ ]:

# comprobamos filas como antes
pd.DataFrame(X).head(10)

In [1]:
# filas de variable objetivo
pd.DataFrame(y).head(10)

NameError: name 'pd' is not defined

**2.1. Transformación de Variables Categóricas.**

Columnas categóricas a transformar:

- `Explicit`: (True/False) → se usará **Label
  Encoding**, al igual que con `Gender`.
- `Time Signature` :  3 valores principales (3, 4 y 5, que representan el
  compás musical de la canción) → se usará **One-Hot Encoding**, igual que con
  `Geography`

**2.1.1. Se Comienza con la Columna Explicit (equivalente a Gender).**

In [ ]:
#aplicamos label encoding a la columna explicit
le2 = LabelEncoder()
X[:, 2] = le2.fit_transform(X[:, 2])
pd.DataFrame(X)
# mostramos la transformacion , 0 false, 1 true, orden alfabetico

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,149360.0,4.0,0,0.766,0.868,2.0,-4.73,1.0,0.0499,0.0928,0.0,0.773,0.377,124.999
1,122659.0,4.0,1,0.626,0.836,8.0,-4.597,1.0,0.0391,0.268,0.000003,0.0902,0.845,90.258
2,205000.0,4.0,0,0.72,0.583,9.0,-7.439,1.0,0.0992,0.0199,0.0,0.124,0.216,145.903
3,141586.0,5.0,0,0.577,0.467,2.0,-8.496,0.0,0.349,0.568,0.000015,0.174,0.41,84.41
4,171291.0,4.0,0,0.791,0.512,8.0,-7.356,0.0,0.382,0.37,0.000015,0.1,0.656,90.078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,145882.0,4.0,1,0.816,0.538,6.0,-6.354,0.0,0.0617,0.0142,0.000485,0.099,0.156,97.055
1211,210367.0,4.0,0,0.586,0.664,2.0,-7.599,0.0,0.0332,0.494,0.000004,0.447,0.337,147.984
1212,185118.0,4.0,0,0.704,0.898,7.0,-2.674,0.0,0.0537,0.167,0.0,0.763,0.962,165.971
1213,235812.0,4.0,1,0.615,0.959,7.0,-3.457,0.0,0.0375,0.00119,0.000165,0.188,0.316,139.983
1214,203571.0,4.0,0,0.581,0.678,6.0,-4.017,0.0,0.0501,0.167,0.000298,0.0866,0.624,171.94

In [ ]:
# se aplica one hot encoding a la columna del compas musical, usando columnTransformer como en la primera parte
ct2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct2.fit_transform(X))

pd.DataFrame(X)
#mostramos la transformacion, ahora las primeras columnas estan binarizadas por cada compas musical que hay en la playlist

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0.0,0.0,1.0,0.0,149360.0,0,0.766,0.868,2.0,-4.73,1.0,0.0499,0.0928,0.0,0.773,0.377,124.999
1,0.0,0.0,1.0,0.0,122659.0,1,0.626,0.836,8.0,-4.597,1.0,0.0391,0.268,0.000003,0.0902,0.845,90.258
2,0.0,0.0,1.0,0.0,205000.0,0,0.72,0.583,9.0,-7.439,1.0,0.0992,0.0199,0.0,0.124,0.216,145.903
3,0.0,0.0,0.0,1.0,141586.0,0,0.577,0.467,2.0,-8.496,0.0,0.349,0.568,0.000015,0.174,0.41,84.41
4,0.0,0.0,1.0,0.0,171291.0,0,0.791,0.512,8.0,-7.356,0.0,0.382,0.37,0.000015,0.1,0.656,90.078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,0.0,0.0,1.0,0.0,145882.0,1,0.816,0.538,6.0,-6.354,0.0,0.0617,0.0142,0.000485,0.099,0.156,97.055
1211,0.0,0.0,1.0,0.0,210367.0,0,0.586,0.664,2.0,-7.599,0.0,0.0332,0.494,0.000004,0.447,0.337,147.984
1212,0.0,0.0,1.0,0.0,185118.0,0,0.704,0.898,7.0,-2.674,0.0,0.0537,0.167,0.0,0.763,0.962,165.971
1213,0.0,0.0,1.0,0.0,235812.0,1,0.615,0.959,7.0,-3.457,0.0,0.0375,0.00119,0.000165,0.188,0.316,139.983
1214,0.0,0.0,1.0,0.0,203571.0,0,0.581,0.678,6.0,-4.017,0.0,0.0501,0.167,0.000298,0.0866,0.624,171.94

**2.1.2. Comprobando la Salida.**

_✍️ Completá acá tu propia verificación (equivalente a la sección 1.1.2 de la Parte 1):_
mirá la primera fila de la tabla resultante e indicá, según el orden de las columnas one-hot
generadas (podés confirmarlo con `ct2.named_transformers_['encoder'].categories_`), a qué compás
musical corresponde esa canción.

**2.2. Escalar y Estandarizar las Características.**

In [ ]:

# estandarizar cada columna a media de 0 y desviacion estandar de 1
sc2 = StandardScaler()
scaled_data_2 = sc2.fit_transform(X)
pd.DataFrame(scaled_data_2).head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,-0.049752,-0.198368,0.241583,-0.122628,-0.828254,-0.840512,0.698510,1.332060,-0.937231,0.515350,1.150276,-0.644022,-0.684834,-0.175623,4.655161,-0.716714,0.143973
1,-0.049752,-0.198368,0.241583,-0.122628,-1.451622,1.189751,-0.452133,1.129042,0.742320,0.554507,1.150276,-0.761357,0.131638,-0.175592,-0.705125,1.620752,-0.981647
2,-0.049752,-0.198368,0.241583,-0.122628,0.470731,-0.840512,0.320442,-0.476073,1.022245,-0.282200,1.150276,-0.108408,-1.024565,-0.175623,-0.439780,-1.520842,0.821269
3,-0.049752,-0.198368,-4.139363,8.154753,-1.009748,-0.840512,-0.854858,-1.212014,-0.937231,-0.593389,-0.869356,2.605516,1.529706,-0.175472,-0.047257,-0.551893,-1.171124
4,-0.049752,-0.198368,0.241583,-0.122628,-0.316248,-0.840512,0.903982,-0.926520,0.742320,-0.257765,-0.869356,2.964041,0.606981,-0.175464,-0.628190,0.676775,-0.987479
5,-0.049752,-0.198368,0.241583,-0.122628,2.340158,-0.840512,-1.635652,0.843547,-1.217156,1.117120,1.150276,-0.121445,-0.959788,-0.175623,-0.639966,0.337144,-0.698857
6,-0.049752,-0.198368,0.241583,-0.122628,3.196195,1.189751,0.427287,-0.831355,-1.497081,0.145869,-0.869356,-0.658146,0.579019,-0.175623,-0.628975,-0.746682,-0.340542
7,-0.049752,-0.198368,-4.139363,8.154753,0.665719,-0.840512,-0.764451,-0.850388,-0.657306,-1.018514,-0.869356,-0.516909,-0.413609,0.280652,-0.314172,0.536927,-0.225521
8,-0.049752,-0.198368,0.241583,-0.122628,-0.366722,1.189751,-0.567198,-0.215955,1.022245,0.442632,-0.869356,0.226215,-0.390308,-0.175623,-0.700414,-0.746682,-0.990719
9,-0.049752,-0.198368,0.241583,-0.122628,1.354153,-0.840512,0.098532,-0.501450,-0.377381,0.211816,1.150276,-0.129050,-0.791553,-0.175623,-0.659592,-0.786638,-0.701546

In [ ]:

# reescalar cada columna al rango 0 1 con minMaxScaler
scaler2 = MinMaxScaler()
scaled_data_3 = scaler2.fit_transform(X)
pd.DataFrame(scaled_data_3).head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0.0,0.0,1.0,0.0,0.169623,0.0,0.770370,0.884420,0.181818,0.912786,1.0,0.027564,0.093146,0.000000,0.841379,0.387057,0.532527
1,0.0,0.0,1.0,0.0,0.115568,1.0,0.597531,0.851690,0.727273,0.915720,1.0,0.015844,0.269055,0.000003,0.062193,0.867555,0.331973
2,0.0,0.0,1.0,0.0,0.282264,0.0,0.713580,0.592914,0.818182,0.853034,1.0,0.081063,0.019951,0.000000,0.100765,0.221758,0.653202
3,0.0,0.0,0.0,1.0,0.153885,0.0,0.537037,0.474266,0.181818,0.829720,0.0,0.352143,0.570268,0.000015,0.157823,0.420939,0.298213
4,0.0,0.0,1.0,0.0,0.214021,0.0,0.801235,0.520293,0.727273,0.854865,0.0,0.387954,0.371467,0.000015,0.073377,0.673508,0.330934
5,0.0,0.0,1.0,0.0,0.444370,0.0,0.419753,0.805662,0.090909,0.957871,1.0,0.079761,0.033907,0.000000,0.071665,0.603692,0.382358
6,0.0,0.0,1.0,0.0,0.518601,1.0,0.729630,0.535635,0.000000,0.885105,0.0,0.026153,0.365443,0.000000,0.073263,0.380897,0.446200
7,0.0,0.0,0.0,1.0,0.299172,0.0,0.550617,0.532567,0.272727,0.797869,0.0,0.040260,0.151581,0.044121,0.119023,0.644760,0.466694
8,0.0,0.0,1.0,0.0,0.209645,1.0,0.580247,0.634850,0.818182,0.907338,0.0,0.114487,0.156602,0.000000,0.062878,0.380897,0.330356
9,0.0,0.0,1.0,0.0,0.358869,0.0,0.680247,0.588823,0.363636,0.890046,1.0,0.079002,0.070153,0.000000,0.068812,0.372683,0.381879

In [ ]:

# estadisticos descriptivos de los datos ya estandarizados
pd.DataFrame(scaled_data_2).describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
count,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03,1.215000e+03
mean,7.310110e-18,-1.169618e-17,8.772133e-18,-2.119932e-17,-9.356941e-17,5.848088e-18,-3.777865e-15,1.286579e-15,4.093662e-17,-1.590680e-15,-8.772133e-17,-1.543895e-15,1.040960e-15,1.842148e-16,7.602515e-16,3.567334e-16,-2.959133e-15
std,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00,1.000412e+00
min,-4.975186e-02,-1.983680e-01,-4.139363e+00,-1.226279e-01,-2.784366e+00,-8.405121e-01,-4.430072e+00,-4.153751e+00,-1.497081e+00,-1.166813e+01,-8.693563e-01,-9.199774e-01,-1.117166e+00,-1.756229e-01,-1.132974e+00,-2.599623e+00,-2.844860e+00
25%,-4.975186e-02,-1.983680e-01,2.415830e-01,-1.226279e-01,-6.830754e-01,-8.405121e-01,-5.959636e-01,-6.473693e-01,-9.372310e-01,-3.410820e-01,-8.693563e-01,-6.407627e-01,-7.796699e-01,-1.756229e-01,-6.281903e-01,-7.616653e-01,-8.018090e-01
50%,-4.975186e-02,-1.983680e-01,2.415830e-01,-1.226279e-01,-9.581227e-02,-8.405121e-01,1.231885e-01,7.588377e-02,1.824698e-01,1.806087e-01,-8.693563e-01,-3.854496e-01,-2.831227e-01,-1.756229e-01,-4.005273e-01,-7.482875e-03,-2.806660e-01
75%,-4.975186e-02,-1.983680e-01,2.415830e-01,-1.226279e-01,5.051668e-01,1.189751e+00,7.231669e-01,7.801039e-01,7.423201e-01,5.459688e-01,1.150276e+00,2.914016e-01,5.067858e-01,-1.744380e-01,3.217140e-01,7.691751e-01,6.786912e-01
max,2.009975e+01,5.041135e+00,2.415830e-01,8.154753e+00,8.747746e+00,1.189751e+00,2.227222e+00,2.048969e+00,1.582096e+00,1.679439e+00,1.150276e+00,9.091554e+00,3.524283e+00,1.016593e+01,5.746374e+00,2.265053e+00,2.767686e+00

In [ ]:
# lo mismo para los datos escalados (usando minMaxSaler)
pd.DataFrame(scaled_data_3).describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
count,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000
mean,0.002469,0.037860,0.944856,0.014815,0.241445,0.413992,0.665446,0.669666,0.486195,0.874176,0.430453,0.091892,0.240693,0.016982,0.164692,0.534388,0.506875
std,0.049649,0.190936,0.228355,0.120861,0.086750,0.492750,0.150273,0.161286,0.324896,0.074951,0.495343,0.099926,0.215539,0.096737,0.145422,0.205648,0.178246
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,0.182212,0.000000,0.575926,0.565297,0.181818,0.848623,0.000000,0.027889,0.072713,0.000000,0.073377,0.377817,0.364015
50%,0.000000,0.000000,1.000000,0.000000,0.233136,0.000000,0.683951,0.681900,0.545455,0.887708,0.000000,0.053391,0.179695,0.000000,0.106470,0.532849,0.456868
75%,0.000000,0.000000,1.000000,0.000000,0.285250,1.000000,0.774074,0.795434,0.727273,0.915080,1.000000,0.120998,0.349880,0.000115,0.211457,0.692502,0.627799
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

### Conclusión Parte 2

_✍️ Completá acá tu propia conclusión comparando ambos datasets, por ejemplo:_
- ¿Qué diferencias encontraste entre trabajar con un dataset sin nulos (Churn) y uno con nulos
  reales (playlist)?
- ¿Tiene sentido, para este dataset de canciones, usar StandardScaler o MinMaxScaler antes de
  entrenar un modelo? ¿Por qué?
- ¿Qué otra columna categórica de la playlist te hubiera parecido interesante transformar (por
  ejemplo, `Genres` o `Key`)?